service: telegram-bot

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    TELEGRAM_BOT_TOKEN: 7865623009:AAHaE6moxB6jQPDzeTpjS-yTqxltWGnov10

functions:
  webhook:
    handler: handler.telegramWebhook
    events:
      - http:
          path: webhook
          method: post